version: '3.8'

# Services
services:
  # Server service
  server:
    image: pradippipaliya/abc-master_server:latest
    container_name: backend
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DB_URL=mongodb+srv://pradippipaliya02:pradip2002@cluster0.bqa5czs.mongodb.net/
      - JWT_SECRET_KEY=2FxXT1NTf2K1Mo4i6AOvtdI
      - JWT_EXPIRES=7d
      - ACTIVATION_SECRET=Hellogoodmorning
      - SMPT_HOST=smtp.gmail.com
      - SMPT_PORT=465
      - SMPT_PASSWORD=hncwvkymkxfljjok
      - SMPT_MAIL=vivek.kakadiya111@gmail.com
      - STRIPE_API_KEY=pk_test_51NCn5ESHYEKWZyIQqCZ3bff3X7zmwAxMhwVPYqaYVl2Qyixqp6z2bUnlkaaSIB4B2qRPAX8e1fErmlpwF5dFYnVO00uBfSmn05
      - STRIPE_SECRET_KEY=sk_test_51NCn5ESHYEKWZyIQENbUqwAbyaRJCJWz6tnTVFL0nDAVasdo0G6stYYUvVdUAo9Z1ofYOi442vPOknrKnX9CEtXc00JUn93Kpd
    depends_on:
      - mongodb

  # Client service
  client:
    image: pradippipaliya/abc-master_client:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
# Volumes define
volumes:
  mongodb_data: