name: Build Docker Image and Push to Github Container Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker buildx
        run: |
          mkdir -p $HOME/.docker/cli-plugins
          wget https://github.com/docker/buildx/releases/download/v0.11.2/buildx-v0.11.2.linux-amd64
          chmod +x buildx-v0.11.2.linux-amd64
          mv buildx-v0.11.2.linux-amd64 $HOME/.docker/cli-plugins/docker-buildx
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1

      - name: Build and push Docker image
        run: |
          cd client/
          docker build . -t pradippipaliya/abc-master_client:latest
          cd ..
          cd server/
          docker build . -t pradippipaliya/abc-master_server:latest
          docker push pradippipaliya/abc-master_client:latest
          docker push pradippipaliya/abc-master_server:latest
          
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Pull the latest Docker image and restart the container
            docker-compose down
            docker rmi pradippipaliya/abc-master_client:latest
            docker rmi pradippipaliya/abc-master_server:latest
            docker pull pradippipaliya/abc-master_client:latest
            docker pull pradippipaliya/abc-master_server:latest
            pwd
            cd /home/ubuntu/abc
            docker-compose up -d 
